name: "Linux Discovery"
description: "Detect Linux distro and install required packages for Wails build"
runs:
  using: "composite"
  steps:
    - name: Linux Discovery
      if: runner.os == 'Linux'
      id: linux_discovery
      run: |
        sudo apt-get -yq update
        DISTRO=$(lsb_release -rs)
        if [[ "$DISTRO" == "20.04" ]]; then
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
        elif [[ "$DISTRO" == "22.04" ]]; then
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
        elif [[ "$DISTRO" == "24.04" ]]; then
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
        else
          echo "Unsupported Linux distribution: $DISTRO"
          exit 1
        fi
        echo "DISTRO=$DISTRO" >> "$GITHUB_OUTPUT"
      shell: bash
outputs:
  DISTRO:
    description: "Detected Linux distribution version"
    value: ${{ steps.linux_discovery.outputs.DISTRO }}
