name: "Wails v2 (full pipeline)"
description: "Runs the full Wails v2 build pipeline: discovery, options, setup (Go/Deno/Wails), build, sign, and package"
inputs:
  build:
    description: "Whether to run the build"
    required: false
    default: "true"
  sign:
    description: "Sign the build (macOS/Windows)"
    required: false
    default: "false"
  package:
    description: "Upload artifacts and release on tag"
    required: false
    default: "true"
  nsis:
    description: "Build a Windows Installer"
    required: false
    default: "false"
  build-name:
    description: "The name of the binary/app bundle"
    required: true
  build-cache:
    description: "Enable Go cache"
    required: false
    default: "true"
  build-platform:
    description: "Platform to build for (e.g., linux/amd64, windows/amd64, darwin/universal)"
    required: false
    default: "darwin/universal"
  build-tags:
    description: "Build tags to pass to Go compiler. Must be quoted. Space or comma (but not both) separated"
    required: false
    default: "false"
  build-obfuscate:
    description: "Obfuscate (garble) the build"
    required: false
    default: "false"
  wails-version:
    description: "Wails version to use"
    required: false
    default: "latest"
  wails-build-webview2:
    description: "WebView2 installer method [download,embed,browser,error]"
    required: false
    default: "download"
  go-version:
    description: "Go version"
    required: false
    default: "1.23"
  node-version:
    description: "Node js version (unused by pipeline but kept for compatibility)"
    required: false
    default: "18.x"
  deno-build:
    description: "Deno command to run (optional, ENV-first)"
    required: false
    default: ""
  app-working-directory:
    description: "App working directory"
    required: false
    default: "."
  deno-working-directory:
    description: "Deno working directory"
    required: false
    default: "."
  deno-version:
    description: "Deno version"
    required: false
    default: "v1.20.x"
  sign-macos-app-id:
    required: false
    default: ''
    description: ""
  sign-macos-apple-password:
    required: false
    default: ''
    description: ""
  sign-macos-app-cert:
    required: false
    default: ''
    description: ""
  sign-macos-app-cert-password:
    required: false
    default: ''
    description: ""
  sign-macos-installer-id:
    required: false
    default: ''
    description: ""
  sign-macos-installer-cert:
    required: false
    default: ''
    description: ""
  sign-macos-installer-cert-password:
    required: false
    default: ''
    description: ""
  sign-windows-cert:
    required: false
    default: ''
    description: ""
  sign-windows-cert-password:
    required: false
    default: ''
    description: ""
  wails-dev-build:
    description: "Use provided wails binary instead of installing"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Linux Discovery
      id: linux_discovery
      uses: actions/linux-discovery

    - name: Compute Build Options
      id: build_options
      uses: actions/build-options
      with:
        build-obfuscate: ${{ inputs.build-obfuscate }}
        build-tags: ${{ inputs.build-tags }}
        nsis: ${{ inputs.nsis }}
        distro: ${{ steps.linux_discovery.outputs.DISTRO }}

    - name: Setup toolchains (Go, Deno, Wails)
      uses: actions/setup
      with:
        go-version: ${{ inputs.go-version }}
        build-cache: ${{ inputs.build-cache }}
        build-obfuscate: ${{ inputs.build-obfuscate }}
        deno-build: ${{ inputs.deno-build }}
        deno-version: ${{ inputs.deno-version }}
        deno-working-directory: ${{ inputs.deno-working-directory }}
        wails-version: ${{ inputs.wails-version }}
        wails-dev-build: ${{ inputs.wails-dev-build }}

    - name: Build Wails app
      uses: actions/build-wails
      with:
        build: ${{ inputs.build }}
        app-working-directory: ${{ inputs.app-working-directory }}
        build-platform: ${{ inputs.build-platform }}
        build-name: ${{ inputs.build-name }}
        wails-build-webview2: ${{ inputs.wails-build-webview2 }}
        build-options: ${{ steps.build_options.outputs.BUILD_OPTIONS }}

    - name: Sign & notarize (macOS)
      uses: actions/sign-macos
      with:
        sign: ${{ inputs.sign }}
        app-working-directory: ${{ inputs.app-working-directory }}
        build-name: ${{ inputs.build-name }}
        sign-macos-apple-password: ${{ inputs.sign-macos-apple-password }}
        sign-macos-app-id: ${{ inputs.sign-macos-app-id }}
        sign-macos-app-cert: ${{ inputs.sign-macos-app-cert }}
        sign-macos-app-cert-password: ${{ inputs.sign-macos-app-cert-password }}
        sign-macos-installer-id: ${{ inputs.sign-macos-installer-id }}
        sign-macos-installer-cert: ${{ inputs.sign-macos-installer-cert }}
        sign-macos-installer-cert-password: ${{ inputs.sign-macos-installer-cert-password }}

    - name: Sign (Windows)
      uses: actions/sign-windows
      with:
        sign: ${{ inputs.sign }}
        app-working-directory: ${{ inputs.app-working-directory }}
        build-name: ${{ inputs.build-name }}
        sign-windows-cert: ${{ inputs.sign-windows-cert }}
        sign-windows-cert-password: ${{ inputs.sign-windows-cert-password }}

    - name: Package & release
      uses: actions/package
      with:
        package: ${{ inputs.package }}
        build-name: ${{ inputs.build-name }}
