name: "Package & Release"
description: "Uploads build artifacts and publishes GitHub Release on tag if enabled"
inputs:
  package:
    required: false
    default: "true"
  build-name:
    required: true
  os:
    description: "OS name (optional, from discovery). Defaults to runner.os"
    required: false
    default: ""
  arch:
    description: "Architecture (optional, from discovery). Defaults to detected arch"
    required: false
    default: ""
  tag:
    description: "Git tag (optional, from discovery)."
    required: false
    default: ""
  is-tag:
    description: "Whether the ref is a tag (optional, from discovery)."
    required: false
    default: ""
  short-sha:
    description: "Short commit SHA (optional, from discovery)."
    required: false
    default: ""
  ref:
    description: "Git ref (optional, from discovery)."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Compute artifact name
      id: meta
      shell: bash
      run: |
        set -euo pipefail
        OS_IN="${{ inputs.os }}"
        ARCH_IN="${{ inputs.arch }}"
        TAG_IN="${{ inputs.tag }}"
        SHORT_SHA_IN="${{ inputs.short-sha }}"
        # Resolve OS
        if [ -z "$OS_IN" ]; then
          OS_IN="${{ runner.os }}"
        fi
        # Resolve ARCH (prefer input)
        if [ -z "$ARCH_IN" ]; then
          # Try uname -m; fallback to envs on Windows if needed
          if command -v uname >/dev/null 2>&1; then
            M=$(uname -m || echo unknown)
          else
            M="$PROCESSOR_ARCHITECTURE"
          fi
          case "$M" in
            x86_64|amd64) ARCH_IN="amd64";;
            aarch64|arm64) ARCH_IN="arm64";;
            armv7l) ARCH_IN="armv7";;
            *) ARCH_IN="$M";;
          esac
        fi
        # Resolve revision label (prefer tag)
        if [ -n "$TAG_IN" ]; then
          REV="$TAG_IN"
        else
          if [ -z "$SHORT_SHA_IN" ]; then
            GHS="${GITHUB_SHA:-}"
            SHORT_SHA_IN="${GHS:0:7}"
          fi
          REV="$SHORT_SHA_IN"
        fi
        NAME="${{ inputs.build-name }}_${OS_IN}_${ARCH_IN}_${REV}"
        echo "ARTIFACT_NAME=$NAME" >> "$GITHUB_OUTPUT"
    - name: Debug echo artifact name
      shell: bash
      run: |
        echo "[DEBUG_LOG] ARTIFACT_NAME=${{ steps.meta.outputs.ARTIFACT_NAME }}"
    - uses: actions/upload-artifact@v4
      if: inputs.package == 'true'
      with:
        name: ${{ steps.meta.outputs.ARTIFACT_NAME }}
        path: |
          */bin/
          *\bin\*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: inputs.package == 'true' && startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ steps.meta.outputs.ARTIFACT_NAME }}
        files: |
          */bin/*
