name: "Package & Release"
description: "Uploads build artifacts and publishes GitHub Release on tag if enabled"
inputs:
  package:
    required: false
    default: "true"
  build-name:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      if: inputs.package == 'true'
      with:
        name: Wails Build ${{ runner.os }} ${{ inputs.build-name }}
        path: |
          */bin/
          *\bin\*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: inputs.package == 'true' && startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          */bin/*
