name: "Sign"
description: "Unified signing for macOS and Windows (conditional by OS); notarizes on tags for macOS"
inputs:
  sign:
    required: false
    default: "false"
  app-working-directory:
    required: false
    default: "."
  build-name:
    required: true
  # macOS
  sign-macos-apple-password:
    required: false
    default: ''
  sign-macos-app-id:
    required: false
    default: ''
  sign-macos-app-cert:
    required: false
    default: ''
  sign-macos-app-cert-password:
    required: false
    default: ''
  sign-macos-installer-id:
    required: false
    default: ''
  sign-macos-installer-cert:
    required: false
    default: ''
  sign-macos-installer-cert-password:
    required: false
    default: ''
  # Windows
  sign-windows-cert:
    required: false
    default: ''
  sign-windows-cert-password:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    # macOS signing flow
    - name: Import Code-Signing Certificates for macOS
      if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        keychain-password: ${{ inputs.sign-macos-apple-password }}
        p12-file-base64: ${{ inputs.sign-macos-app-cert }}
        p12-password: ${{ inputs.sign-macos-app-cert-password }}
    - name: Import Code-Signing Certificates for macOS Installer
      if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        keychain-password: ${{ inputs.sign-macos-apple-password }}
        p12-file-base64: ${{ inputs.sign-macos-installer-cert }}
        p12-password: ${{ inputs.sign-macos-installer-cert-password }}
        create-keychain: false
    - name: Sign macOS .app with gon
      if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      working-directory: ${{ inputs.app-working-directory }}
      env:
        APPLE_PASSWORD: ${{ inputs.sign-macos-apple-password }}
      run: |
        echo "Signing Package"
        gon -log-level=info ./build/darwin/gon-sign.json
    - name: Build .app zip file
      if: runner.os == 'macOS'
      working-directory: ${{ inputs.app-working-directory }}
      shell: bash
      run: |
        ditto -c -k --keepParent ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.app ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.app.zip
    - name: Build Installer (signed)
      if: runner.os == 'macOS' && inputs.sign != 'false' && inputs.sign-macos-installer-id != '' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      working-directory: ${{ inputs.app-working-directory }}
      run: |
        productbuild --sign '${{ inputs.sign-macos-installer-id }}' --component ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.app /Applications ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.pkg
    - name: Build Installer (unsigned)
      if: runner.os == 'macOS' && inputs.sign-macos-installer-id == '' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      working-directory: ${{ inputs.app-working-directory }}
      run: |
        productbuild --component ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.app /Applications ${{ inputs.app-working-directory }}/build/bin/${{ inputs.build-name }}.pkg
    - name: Notarize Installer and zip with gon
      if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      working-directory: ${{ inputs.app-working-directory }}
      env:
        APPLE_PASSWORD: ${{ inputs.sign-macos-apple-password }}
      run: |
        gon -log-level=info ${{ inputs.app-working-directory }}/build/darwin/gon-notarize.json

    # Windows signing flow
    - name: Sign Windows binaries
      shell: powershell
      if: runner.os == 'Windows' && inputs.sign != 'false' && inputs.sign-windows-cert != ''
      working-directory: ${{ inputs.app-working-directory }}
      run: |
        echo "Creating certificate file"
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ inputs.sign-windows-cert }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
        echo "Signing our binaries"
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd sha256 /tr http://ts.ssl.com /f certificate\certificate.pfx /p '${{ inputs.sign-windows-cert-password }}' .\build\bin\${{ inputs.build-name }}.exe
        echo "Signing Installer"
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd sha256 /tr http://ts.ssl.com /f certificate\certificate.pfx /p '${{ inputs.sign-windows-cert-password }}' .\build\bin\${{ inputs.build-name }}-amd64-installer.exe
