name: "Options"
description: "Compute BUILD_OPTIONS string for builds based on inputs and discovery outputs"
inputs:
  build-obfuscate:
    description: "Obfuscate the build"
    required: false
    default: "false"
  build-tags:
    description: "Build tags to pass to Go compiler. Must be quoted. Space or comma (but not both) separated"
    required: false
    default: "false"
  nsis:
    description: "Include -nsis flag"
    required: false
    default: "false"
  distro:
    description: "Linux distro version (e.g., 24.04). Optional; if 24.04 and no explicit webkit tag provided, add webkit2_41"
    required: false
    default: ""
outputs:
  BUILD_OPTIONS:
    description: "Computed build options"
    value: ${{ steps.compute.outputs.BUILD_OPTIONS }}
runs:
  using: "composite"
  steps:
    - id: compute
      name: Compute build options
      shell: bash
      env:
        DISTRO: ${{ inputs.distro }}
      run: |
        build_options=""
        if ${{ inputs.build-obfuscate == 'true' }}; then
          build_options+=" -obfuscated"
        fi
        if [[ "${{ inputs.build-tags }}" != "false" ]]; then
          tags_string="${{ inputs.build-tags }}"
          if [[ "$DISTRO" == '24.04' ]]; then
            tags_string+=" webkit2_41"
          fi
          build_options+=" -tags $tags_string"
        elif [[ "${{ inputs.build-tags }}" == "false" && "$DISTRO" == '24.04' ]]; then
          build_options+=" -tags webkit2_41"
        fi
        if ${{ inputs.nsis == 'true' }}; then
          build_options+=" -nsis"
        fi
        echo "BUILD_OPTIONS=$build_options" >> "$GITHUB_OUTPUT"
